// Copyright 2025 The CUE Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cmd

import (
	"encoding/json"
	"fmt"
	"os/exec"
	"regexp"
	"strings"
)

const trybotMessageTag = "autogenerated:gerritstatusupdater-trybot"

// gerritChangeMessage represents a message on a Gerrit change.
type gerritChangeMessage struct {
	Message string       `json:"message"`
	Tag     string       `json:"tag"`
	Date    string       `json:"date"`
	Author  gerritAuthor `json:"author"`
}

// gerritChangeDetail represents the detail of a Gerrit change,
// including its messages.
type gerritChangeDetail struct {
	Messages []gerritChangeMessage `json:"messages"`
}

// ghJob represents a GitHub Actions job.
type ghJob struct {
	Name       string `json:"name"`
	Conclusion string `json:"conclusion"`
	HTMLURL    string `json:"html_url"`
	ID         int64  `json:"id"`
}

// actionRunRe matches GitHub Actions run URLs and captures owner, repo, and run ID.
var actionRunRe = regexp.MustCompile(`https://github\.com/([^/]+)/([^/]+)/actions/runs/(\d+)`)

// fetchTrybotResult fetches the latest trybot result for a Gerrit change.
// If the trybot failed, it fetches the failed job logs from GitHub Actions.
func fetchTrybotResult(change string) (string, error) {
	changeNumber, err := resolveChangeNumber(change)
	if err != nil {
		return "", err
	}

	// Fetch change detail with messages.
	body, err := gerritAPI(fmt.Sprintf("/a/changes/%s/detail?o=MESSAGES", changeNumber))
	if err != nil {
		return "", err
	}

	var detail gerritChangeDetail
	if err := json.Unmarshal(body, &detail); err != nil {
		return "", fmt.Errorf("parsing Gerrit change detail: %w", err)
	}

	// Find the latest trybot message (last one wins).
	var latest *gerritChangeMessage
	for i := range detail.Messages {
		if detail.Messages[i].Tag == trybotMessageTag {
			latest = &detail.Messages[i]
		}
	}
	if latest == nil {
		return "No trybot results found for this change.", nil
	}

	var b strings.Builder
	fmt.Fprintf(&b, "Latest trybot message (%s, %s):\n%s\n", latest.Author.Name, latest.Date, latest.Message)

	// Check if this is a failure by looking for a negative vote or "failed" in the message.
	if !strings.Contains(latest.Message, "FAIL") && !strings.Contains(latest.Message, "fail") && !strings.Contains(latest.Message, "-1") {
		return b.String(), nil
	}

	// Extract GitHub Actions run URLs from the message.
	matches := actionRunRe.FindAllStringSubmatch(latest.Message, -1)
	if len(matches) == 0 {
		return b.String(), nil
	}

	// Fetch failed jobs for each run URL.
	for _, match := range matches {
		owner, repo, runID := match[1], match[2], match[3]
		failedJobs, err := fetchFailedJobs(owner, repo, runID)
		if err != nil {
			fmt.Fprintf(&b, "\nError fetching jobs for %s/%s run %s: %v\n", owner, repo, runID, err)
			continue
		}
		if len(failedJobs) == 0 {
			fmt.Fprintf(&b, "\nNo failed jobs found for %s/%s run %s.\n", owner, repo, runID)
			continue
		}

		for _, job := range failedJobs {
			fmt.Fprintf(&b, "\n--- Failed job: %s ---\n", job.Name)
			fmt.Fprintf(&b, "URL: %s\n", job.HTMLURL)

			logs, err := fetchJobLogs(owner, repo, job.ID)
			if err != nil {
				fmt.Fprintf(&b, "Error fetching logs: %v\n", err)
				continue
			}
			fmt.Fprintf(&b, "\n%s\n", logs)
		}
	}

	return b.String(), nil
}

// fetchFailedJobs uses the gh CLI to get failed jobs for a GitHub Actions run.
func fetchFailedJobs(owner, repo, runID string) ([]ghJob, error) {
	out, err := exec.Command("gh", "api",
		fmt.Sprintf("repos/%s/%s/actions/runs/%s/jobs", owner, repo, runID),
		"--jq", `.jobs[] | select(.conclusion == "failure") | {name, conclusion, html_url, id}`,
	).Output()
	if err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			return nil, fmt.Errorf("%s: %s", err, exitErr.Stderr)
		}
		return nil, err
	}

	// gh --jq outputs one JSON object per line (not an array).
	var jobs []ghJob
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		if line == "" {
			continue
		}
		var job ghJob
		if err := json.Unmarshal([]byte(line), &job); err != nil {
			return nil, fmt.Errorf("parsing job JSON: %w", err)
		}
		jobs = append(jobs, job)
	}
	return jobs, nil
}

// fetchJobLogs uses the gh CLI to fetch logs for a specific job,
// returning only the error-relevant portion.
func fetchJobLogs(owner, repo string, jobID int64) (string, error) {
	out, err := exec.Command("gh", "api",
		fmt.Sprintf("repos/%s/%s/actions/jobs/%d/logs", owner, repo, jobID),
	).Output()
	if err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			return "", fmt.Errorf("%s: %s", err, exitErr.Stderr)
		}
		return "", err
	}

	return extractFailedSteps(string(out)), nil
}

// stripTimestamp removes the GitHub Actions timestamp prefix from a log line.
// For example, "2026-03-13T20:17:01.8533283Z some text" becomes "some text".
func stripTimestamp(line string) string {
	if idx := strings.Index(line, "Z "); idx != -1 && idx < 40 {
		return line[idx+2:]
	}
	return line
}

// extractFailedSteps extracts only the GitHub Actions steps that contain
// errors. Steps are delimited by ##[group]/##[endgroup] markers. This
// avoids returning the full job log (which can be very large) when only
// a small portion is relevant.
func extractFailedSteps(logs string) string {
	lines := strings.Split(logs, "\n")

	// First pass: split into steps, tracking which contain errors.
	type step struct {
		lines    []string
		hasError bool
	}
	var steps []step
	var current step

	for _, line := range lines {
		content := stripTimestamp(line)

		if strings.HasPrefix(content, "##[group]") {
			// Start a new step; save the previous one.
			if len(current.lines) > 0 {
				steps = append(steps, current)
			}
			current = step{}
		}

		current.lines = append(current.lines, content)

		if strings.HasPrefix(content, "##[error]") {
			current.hasError = true
		}
	}
	if len(current.lines) > 0 {
		steps = append(steps, current)
	}

	// Collect only steps that contain errors.
	var result []string
	for _, s := range steps {
		if s.hasError {
			result = append(result, strings.Join(s.lines, "\n"))
		}
	}

	if len(result) > 0 {
		return strings.Join(result, "\n\n")
	}

	// Fallback: no ##[error] markers found; return the last 50 lines.
	start := max(len(lines)-50, 0)
	stripped := make([]string, 0, len(lines)-start)
	for _, line := range lines[start:] {
		stripped = append(stripped, stripTimestamp(line))
	}
	return strings.Join(stripped, "\n")
}
